let tasks = [];
let current='all', completed=[], snoozed=[];
const labels={urgent:'ACT NOW',upcoming:'UPCOMING',later:'LATER'};
const icons={Gmail:'M',Calendar:'▣','College portal':'C',Figma:'F','HDFC Bank':'H',WhatsApp:'W',Manual:'+'};
function sourceMarkup(task){return task.sources.map(x=>`<span class="source-dot">${icons[x]||x[0]}</span>`).join('')+`<span>${task.sources.join(' + ')} · ${task.alerts} alert${task.alerts!==1?'s':''} grouped</span>`}
function taskMarkup(t){return `<article class="task-card"><span class="priority-rail ${t.section}"></span><div class="task-icon ${t.tone}">${t.icon}</div><div class="task-main"><div class="task-title-row"><span class="task-title">${t.title}</span><span class="pill ${t.section}">${t.section==='urgent'?'HIGH':t.section.toUpperCase()}</span></div><p class="description">${t.description}</p><div class="meta">${sourceMarkup(t)}<span class="due ${t.section==='urgent'?'urgent':''}">${t.due}</span></div></div><div class="actions"><button class="action why" onclick="showWhy(${t.id})">Why this?</button><button class="action" onclick="snoozeTask(${t.id})">Snooze</button><button class="action check" onclick="completeTask(${t.id})" title="Mark done">✓</button></div></article>`}
function render(){let pool=tasks.filter(t=>!completed.includes(t.id)&&!snoozed.includes(t.id));if(current!=='all')pool=pool.filter(t=>t.section===current);let html='';['urgent','upcoming','later'].forEach(section=>{let group=pool.filter(t=>t.section===section);if(group.length)html+=`<div class="section-label">${labels[section]}</div>${group.map(taskMarkup).join('')}`});document.getElementById('feed').innerHTML=html||'<div class="empty"><h2>Your inbox is clear.</h2><p>Nice work — there is nothing demanding attention here.</p></div>';let counts={urgent:0,upcoming:0,later:0};tasks.filter(t=>!completed.includes(t.id)&&!snoozed.includes(t.id)).forEach(t=>counts[t.section]++);document.getElementById('urgentCount').textContent=counts.urgent;document.getElementById('upcomingCount').textContent=counts.upcoming;document.getElementById('laterCount').textContent=counts.later;document.getElementById('allCount').textContent=counts.urgent+counts.upcoming+counts.later;document.getElementById('navCount').textContent=counts.urgent+counts.upcoming+counts.later;document.getElementById('attentionCount').textContent=`${counts.urgent+counts.upcoming+counts.later} thing${counts.urgent+counts.upcoming+counts.later!==1?'s':''}`}
function toast(text){let t=document.getElementById('toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function completeTask(id){completed.push(id);render();toast('Task marked complete. Great progress.')}
function snoozeTask(id){snoozed.push(id);render();toast('Snoozed until tomorrow at 9:00 AM.')}
function showWhy(id){let t=tasks.find(x=>x.id===id);toast(t.why)}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelector('.tab.active').classList.remove('active');b.classList.add('active');current=b.dataset.filter;render()});
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>{let v=b.dataset.view;if(!v)return;if(v==='inbox'){current='all';document.querySelector('.tab.active').classList.remove('active');document.querySelector('[data-filter="all"]').classList.add('active');render()}else if(v==='completed'||v==='snoozed'){document.getElementById('feed').innerHTML=`<div class="empty"><h2>${v==='completed'?'Completed tasks':'Snoozed tasks'}</h2><p>${(v==='completed'?completed:snoozed).length?'Your task history is safely stored on this device.':'Nothing here yet.'}</p></div>`}else if(v==='sources'){showSources()}else toast('Settings will let each user control priority rules and privacy.')});
const dialog=document.getElementById('taskDialog');document.getElementById('addTask').onclick=()=>dialog.showModal();document.getElementById('saveTask').onclick=e=>{let title=document.getElementById('taskTitle').value.trim();if(!title){e.preventDefault();return}let section=document.getElementById('taskPriority').value;let due=document.getElementById('taskDue').value;tasks.push({id:Date.now(),section,title,description:'Added manually to your priority inbox',sources:['Manual'],alerts:1,icon:'✓',tone:'green',due:due==='today'?'Due today':due==='tomorrow'?'Due tomorrow':'Due this week',why:'You chose this priority when you created the task.'});setTimeout(()=>{render();toast('Added to your priority inbox.')},0)};
render();
function showSources(){document.getElementById('feed').innerHTML=`<div class="section-label">YOUR APPROVED SOURCES</div><article class="task-card"><div class="task-icon">◉</div><div class="task-main"><div class="task-title">Nothing is connected yet</div><p class="description">Signal has not received any notification or service data. Connections must be explicitly approved by you and can be removed at any time.</p><div class="meta">For the deployed web version, Gmail and Google Calendar will use their own Google permission screen. A website cannot connect to installed phone apps.</div></div></article>${['Gmail','Google Calendar'].map((x,i)=>`<article class="task-card"><div class="task-icon ${i===1?'orange':''}">${icons[x]}</div><div class="task-main"><div class="task-title">${x}</div><p class="description">Not connected</p></div><div class="actions"><button class="action" onclick="toast('Google authorization will be available once the secure backend is connected.')">Connect</button></div></article>`).join('')}`}
function setUser(user){document.getElementById('profileName').textContent=user.name;document.getElementById('profileInitials').textContent=user.name.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase();document.querySelector('.auth-screen').classList.add('hidden')}
let authMode='register';
const authForm=document.getElementById('authForm');
authForm.addEventListener('submit',e=>{e.preventDefault();let name=document.getElementById('nameInput').value.trim(),email=document.getElementById('emailInput').value.trim();if(authMode==='login'){let saved=JSON.parse(localStorage.getItem('signalUser')||'null');if(!saved||saved.email!==email){toast('No matching prototype account found. Create one first.');return}setUser(saved);return}let user={name,email};localStorage.setItem('signalUser',JSON.stringify(user));setUser(user);toast('Account created. Review your approved sources next.')});
function renderAuthMode(){let login=authMode==='login';document.getElementById('authEyebrow').textContent=login?'WELCOME BACK':'CREATE YOUR SPACE';document.getElementById('authTitle').textContent=login?'Your day, in focus.':'Start with calm.';document.getElementById('authSub').textContent=login?'Sign in to see your personal priority inbox.':'Create a private priority inbox for your notifications.';document.getElementById('nameInput').style.display=login?'none':'';document.querySelector('#nameInput').required=!login;document.getElementById('authSubmit').textContent=login?'Sign in':'Create my account';document.getElementById('authSwitch').innerHTML=login?'New to Signal? <button type="button">Create an account</button>':'Already have an account? <button type="button">Sign in</button>';document.querySelector('#authSwitch button').onclick=()=>{authMode=authMode==='register'?'login':'register';renderAuthMode()}}
renderAuthMode();
document.getElementById('signOut').onclick=()=>{document.querySelector('.auth-screen').classList.remove('hidden');authForm.reset()};
document.getElementById('openSources').onclick=showSources;
